name: ThorpsCore
version: 0.1.2
description: ToDo
main: com.thorpscraft.imasonite.ThorpsCore
author: iMasonite
website: http://www.thorpscraft.com
dev-url: https://github.com/iMasonite/ThorpsCore
softdepend: [Vault]
commands:
  thorps: 
     description: override cmd.
     aliases: th
  returnme: 
      description: override cmd.      
permissions:
  thorpscore.*:
    description: Gives access to all thorpscore commands.
    default: false
    children:
      thorpscore.messages.*: true
  thorpscore.messages.*:
    description: Gives access to all thorpscore message features.
    default: false
    children:
      thorpscore.messages.say: true
  thorpscore.messages.say:
    description: Gives access to /say command.
    default: false
