name: ThorpsCore
version: 0.1.3
description: ToDo
main: com.thorpscraft.imasonite.ThorpsCore
author: iMasonite
website: http://www.thorpscraft.com
dev-url: https://github.com/iMasonite/ThorpsCore
commands:
  ThorpsCore:
    description: Main Command.
    aliases: [thorps, th]
permissions:
  thorpscore.*:
    description: Gives access to all commands
    default: false
    children:
      thorpscore.test: true
  thorpscore.test:
    description: test...
    default: false
    