name: ThorpsCore
version: 0.1.2
description: ToDo
main: com.thorpscraft.imasonite.ThorpsCore
author: iMasonite
website: http://www.thorpscraft.com
dev-url: https://github.com/iMasonite/ThorpsCore
softdepend: [Vault]
commands:

  # Debug #
  returnme: 
      description: override cmd.      
permissions:
  # Global #
  thorpscore.*:
    description: Gives access to all thorpscore commands.
    default: op
    children:
      thorpscore.messages.*: true
        
  # Categoty #      
  thorpscore.messages.*:
    description: Gives access to all thorpscore message features.
    default: op
    children:
      thorpscore.messages.say: true
        
  # Singletons #      
  thorpscore.messages.say:
    description: Gives access to /say command.
    default: op
